export const missingPet = [
  {
    petId: 1,
    petName: "코쇼",
    petType: "고양이",
    petSex: "♀",
    petBreed: "삼색",
    petAge: 2014,
    petMissingDate: "2025-06-17",
    petColor: "노란색,검은색 얼룩무늬",
    petContent: "시흥시 안현동 근방에서 방 창문 뚫고 탈출함",
    missingPoint: "경기도 시흥시 안현동",
  },
  {
    petId: 2,
    petName: "마루",
    petType: "강아지",
    petSex: "♀",
    petBreed: "폼피츠",
    petAge: 2025,
    petMissingDate: "2025-06-18",
    petColor: "흰색",
    petContent: "겁 많은 아이, 산책중 목줄이 풀려서 실종됐습니다.",
    missingPoint: "경기도 시흥시 안현동",
  },
  {
    petId: 3,
    petName: "히니",
    petType: "강아지",
    petSex: "♂",
    petBreed: "비숑 프리제",
    petAge: 2024,
    petMissingDate: "2025-06-19",
    petColor: "흰색",
    petContent: "최근 미용했어요 애교 많습니다. 정왕동 근방에서 실종됐어요",
    missingPoint: "경기도 시흥시 정왕동",
  },
];
